ios-workflow:
    name: iOS Workflow
    # instance_type: mac_mini
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"                
        # https://docs.codemagic.io/code-signing-yaml/signing-ios/
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(ea0bfb6f-6a21-44aa-8077-0786a74e84d4) # <-- Put your encrypted App Store Connect Issuer Id here 
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(ZDL5LJ47DS) # <-- Put your encrypted App Store Connect Key Identifier here 
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2J7Qs4mGEH7XkATw
RpRlocX6YCyGySPVus4UlMVQtwGgCgYIKoZIzj0DAQehRANCAARQj1E07mLWiHCp
ii8nA5mXkgf3zGGxmJfdg93mNqb5Es5r2c41yl1h6sYR6t/8ssxZOgTYmja1puAM
Mqd+VmNO) # <-- Put your encrypted App Store Connect Private Key here 
        CERTIFICATE_PRIVATE_KEY: Encrypted(MIIEowIBAAKCAQEAlkKrtCx/LHRGVRrBBf/K5l7oHLxcqmJAwVuftk8Fts1iaodh
DjJqEsDthKvz1N6FB+fI4FJilry29g5cIP2A+WTP9W2PGSNHWBFW5vCSy4Sh/jMO
ZWOmcdFdwOA99/jZTJXuR3GCUVgD2sAFb/9I4r5El0Gik4eHtcFEtlSf2KPuSB4S
fKF7TD//JUUxOD1H++f7X3JraaIX+my2a+zqnawY03MUaP6v2P/iNugfp3hJgkyv
HJ6D0cpswuR3rVCYh+7hK9wutlnZoQ3KYYTQRyn6MZ6mU3njkLExqIaYcEgjByp6
eAMV+zJNI11KOu53X7CktZEwt/uhue+EvVRb5wIDAQABAoIBADw5To5xQytzEvlr
NrAL3KvGoCtcR5u2s5OMAJBWTcj9upNN3VWOWTtY/hmtvZW09ga8HKPkAUW/L2mh
ScWjNT0/7aXFmpQNsruWf4kiJQPTDgZPOlbiwMRfkL8MYWnw4E80zILv+LZXm3vi
eItx+yl97wncsaeFq5vqcXrOoh52wILSmUVgxQkCPCBx5O2ILr+rfAUTLhO0irvz
OqWnpVKGarJGjjr/avMjUcdp7BD1sFYpD06o97WvKj8FYfBxpZIFGT+TZ/MZvLVq
MNuDc/xRPj5LYQtsBnAT4CST95KMmsmN3ZZoz29mZWilsjUrlM41umcsljThfXPf
6AU/GRkCgYEAxS0yDCGrM40lxBDSfIFMBZM0JQUDmj05h5kDYQ1pKDprK4db3KSp
vqbk29oaZH5oq1FftS5onEQHI3zVSObVa5gS/WqYEle9DwTEwzDvAPvQ3Sk2LhfV
/4v2DcHNmK3LBk3ueSqDt/ESO5xZmpx6P74kw2FlXM35oc1/5jnDzhUCgYEAwxZj
lDWnV8LuFupTSmt6P1clxZqjVlDN0kTWGoEKypUd9zPFlG/YuCMGmRAdXw0rjplP
3XcIb3xPEKWufgqyq2U77MD1Ih/jyx2lVJiQH3e9PTMKg6XGMr8IqIf15pmfKWRU
fF+Xk/3ixv0xt9YRLZC9LfkLqXwiMo0EvC3xvQsCgYEAmch4IjIYPqq1a8fbArQt
QKPgpYbVmnRp7DIRCp7VB0UY1OhLYzkiEspD8JyYvQxCQmvDA6JggJAmKS1xg9xV
VAdVuERsutGnaJFFjR8bKV89NWCxGx4ID7lvfKdM3OmfURlzBxl7hfkFSWzWDdpB
FnoMXj4WOl2Ddwi52ivvZUkCgYBPgxWM950/6MQPdOwDnfCSVlufwVonOQHaXJIC
9WtHjCVNdr1ltXxX+Hac9fNypTSGhzgE5Jn8jmbPOyf2WTffIYCeCzsd8G9wfqG+
6/t5x9zKT75OT8eLMU8/GUMA/MXhIfJJStDF0amXPuT/r3EK6D4iuammJ2Dsx4sR
g4xOZwKBgAHYQ7+gzTYNv2LY5jK6/ZA+bCnKzb1n//OL1zzaVVIUifbJPZhDKdf4
bdYtn9Rxm5h7mjxWECfoVoBClcsL7G2zGk9ZwbNtkJQGbN2xV3A6HTzPLfVto1jT
qYHDXF6aoHc23/6n5Ock1hnm8SKkjyCa9nRUawaVyDS2w55rN24P) # <-- Put your encrypted Certificate Private Key here 
        APPLE_ID: Encrypted(pishnjak@ya.ru) # <-- Put your encrypted Apple Id email address here
        APPLE_APP_SPECIFIC_PASSWORD: Encrypted(030303aA) # <-- Put your encrypted App Specific password here
        BUNDLE_ID: "ru.barnlab.kassis" # <-- Put your bundle id here
        APP_STORE_ID: 1111111111 # <-- Use the TestFlight Apple id number (An automatically generated ID assigned to your app) found under General > App Information > Apple ID. 
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Flutter analyze
        script: |
          cd . && flutter analyze
      - name: Flutter unit tests
        script: |
          cd . && flutter test
        ignore_failure: true          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email      
        notify:
          success: true     # To receive a notification when a build succeeds
          failure: false    # To not receive a notification when a build fails
      slack: 
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#builds"
        notify_on_build_start: true   # To receive a notification when a build starts
        notify:
          success: true               # To receive a notification when a build succeeds
          failure: false              # To not receive a notification when a build fails
      app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
        apple_id: pishnjak@ya.ru    
        password: 030303aA
