# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do

# Comment the next line if you don't want to use dynamic frameworks

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
# Pods for Runner


  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
     end
  end
end

